# Generated by Django 2.0.7 on 2020-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='summary',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
