# Generated by Django 2.0.7 on 2020-04-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
